### ISSUE TITLE
Make infos about the current table available for the "Include in Report" functionality.

### ISSUE THREAD

**Issue by therter** [clarity-h2020/table-components#12]
The table-components should deliver data about the current table, so that the "Include in Report" functionality can use this information to generate a comment about the table.

See also: clarity-h2020/map-component#22

**Comment by p-a-s-c-a-l** [comment]
Status?

**Comment by therter** [comment]
The same mechanism that was used for the [map](https://github.com/clarity-h2020/map-component/issues/22) can be used here. Which informations about the table are useful? Perhaps the data from the request.

**Comment by p-a-s-c-a-l** [comment]
The title of the table is just enough.
