### ISSUE TITLE
Units in HC and EE table

### ISSUE THREAD

**Issue by therter** [clarity-h2020/table-components#14]
The difference to the baseline value should be shown with an unit. So the table-rest-api should provide the units

**Comment by p-a-s-c-a-l** [comment]
Status?

**Comment by p-a-s-c-a-l** [comment]
![grafik](https://user-images.githubusercontent.com/1788226/60326684-6aed8b80-998a-11e9-88a1-58412183b016.png)

Still unresolved. See https://github.com/clarity-h2020/table-state-rest-api/issues/5

@RobAndGo @ghilbrae @therter @negroscuro 

What is the unit? +56 seems pretty high. I hope it not °C.

**Comment by ghilbrae** [comment]
The EE request/response already is taking into account that a unit should be specified. As you have pointed out and is described in that issue, it is still something TBD for HC. See @RobAndGo response to the issue.
 
> What is the unit? +56 seems pretty high. I hope it not °C.

I suspect it might be, checking other values it makes sense. Also, considering how hot it is today it doesn't seem too unrealistic :weary:

**Comment by maesbri** [comment]
"uom" property has been added to the grid_band_info object
