### ISSUE TITLE
Implement HC-LE Table

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/table-components#2]
Implement the HC-LE Table according to the Mock-Up and following the approach described [here](https://github.com/clarity-h2020/csis/issues/46#issue-390262842).

### HC-LE Table GUI

![grafik](https://user-images.githubusercontent.com/1788226/49883532-39b8ce00-fe33-11e8-96ce-ad25dce698cd.png)

**Important Note:** The the Mock-Up seems to be outdated / invalid (to be discussed [here](https://github.com/clarity-h2020/csis/issues/45)). So at the the moment we should re-use the plain [HC-Table](https://github.com/clarity-h2020/table-components/issues/1). 

### HC-LE Table state model

tbd

### Mapping Data Package to HC-LE Table state model

tbd

**Comment by p-a-s-c-a-l** [comment]
@humerh @bernhardsk 

Hazard with Local effects is now calculated in Emikat, right? What is the result of HC-LE calculation? Same as HC?  = Events? or Temperature? Is it calculated for all events (RCP/time period) or just for the 6 events [selected](https://github.com/clarity-h2020/docker-drupal/issues/58) by the user?

**Comment by humerh** [comment]
Now the result of Local effect calculation is also available as  WMS-Maps:

https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Aview.2974&bbox=4672000.0%2C1979500.0%2C4687500.0%2C1988000.0&width=768&height=421&srs=EPSG%3A3035&format=image%2Fgif&CQL_FILTER=PROJECT_REF=1%20and%20PERIOD=%27Baseline%27%20AND%20RCP=%27Baseline%27%20AND%20FREQUENCE=%27Rare%27%20AND%20SZ_ID=2846&styles=T_A

In this link you can adapt the follwing parameters:

PROJECT_REF=1   ... (for future selection of an alternate ADAPTATION variants)
PERIOD='Baseline'   ... (Alternatives are: '20110101-20401231', '20410101-20701231'  and '20710101-21001231')
RCP='Baseline'  ...  (Alternatives are: 'rcp26', 'rcp45' and 'rcp85')
FREQUENCE='Rare'   ... (Alternatives are: 'Occassional' or 'Frequent')

@p-a-s-c-a-l , @therter  please test and give me feedback, if this approach is ok.

SZ_ID=2846    has to be set to the current $emikatID

styles=T_A    for Apparent temparature
styles=T_TMRT   for Mean Radiant Temperature
styles=T_UTCI     for UTCI Temperature

The color schemas (STYLE colors) are currently fixed but not optimized !!!!
