### ISSUE TITLE
Please expose the link for downloading the table data from EMIKAT

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/table-components#21]
As discussed yesterday, @mattia-leone needs a simple way to download the table data in our studies. 

@patrickkaleta and I looked at this today and this would be difficult to do from the drupal side. We do know the variable values but we do not know which data is shown where, so this would need to be hard-coded in drupal - not a good idea.

Therefore, I propose to do this in the CIS table component. Since the link will not work for normal users, ideally it should be hidden from them, based on their user role. E.g., the link could be shown to users with "editor" role. If a role is not already listed, then the helper module might need to be changed.

**Comment by DenoBeno** [comment]
@p-a-s-c-a-l : this is pretty much irrelevant feature for CSIS, but we badly need to get the results validated. And for this, the results must be easily accessible for climate experts, not just for the technical users that can open a console and see what was called.

**Comment by p-a-s-c-a-l** [comment]
> Since the link will not work for normal users, ideally it should be hidden from them, based on their user role

Hiding the link  / button would be difficult to do from the external application side so it will not be supported in the short term. But why is that needed anyway? What is a 'normal' user? Why shouldn't such a user be allowed to download the data?

But adding a simple [download button](https://github.com/clarity-h2020/simple-table-component/issues/7) which calls EMIKAT CSV API should not be a big issue.

**Comment by DenoBeno** [comment]
My main issue is that "normal user" doesn't have EMIKAT login. But other than that, I don't really care. What I do care about is that @mattia-leone has a quick access to the data.

**Comment by p-a-s-c-a-l** [comment]
Any user needs an "EMIKAT login" ([Basic Authentication](https://github.com/clarity-h2020/emikat/issues/4)) to view data in a table. This is already part of the [user profile](https://github.com/clarity-h2020/docker-drupal/issues/16#issuecomment-516717488).

**Comment by p-a-s-c-a-l** [comment]
File Download is now implemented: https://csis.myclimateservice.eu/study/33/step/1517/view/table

CSV download currently does not work till @humerh fixes [this issue](https://github.com/clarity-h2020/emikat/issues/1#issuecomment-545952761).

**Comment by DenoBeno** [comment]
great!

**Comment by p-a-s-c-a-l** [comment]
done [here](https://github.com/clarity-h2020/simple-table-component/issues/7)
