### ISSUE TITLE
population table seems to be broken

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/table-components#24]
https://csis.myclimateservice.eu/study/35/step/1529/view/table

![image](https://user-images.githubusercontent.com/2961790/68106388-ceac3600-fee1-11e9-8a0e-8ee734a083e1.png)

![image](https://user-images.githubusercontent.com/2961790/68106405-de2b7f00-fee1-11e9-81fa-ce1bf90128a4.png)

**Comment by p-a-s-c-a-l** [comment]
bug fixed

**Comment by DenoBeno** [comment]
thanks
