### ISSUE TITLE
hide/show table columns as a configuration option. 

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/table-components#25]
It would be good if we could add a configuration option to our table components (e.g. to https://csis.myclimateservice.eu/node/1413/edit) that would suppress showing of unnecessary table columns. Even better: also allow to show them in a different order if necessary.

Of course, we *could* change what EMIKAT is spitting out, but this would be a more robust solution/easier to change. It would even allow us to show one EMIKAT output as several tables, e.g. one table tor ambient temperature, second for UTCI and third for the  radiation temperature if and when necessary.

this is how the configuration could look like for the local effects table

![image](https://user-images.githubusercontent.com/2961790/68201582-50739080-ffc2-11e9-83f1-5b8796eada90.png)

by the way, would it be possible to give each cell a 1,2,3...N number or a (N,M) pair corresponding to the place of the grid cell in a study? In my opinion, it would be much easier for the user to talk about cell (3,5) than about the 500mE46360N28055 cell.

**Comment by p-a-s-c-a-l** [comment]
Changing the table layout per table (EE, HV, RA) wouldn't be such a big deal, but making this *configurable* would complete overkill IMHO. 

More important, somebody should define which columns to show and the order. There is validation Task, so we should collect such feedback from end users.

> would it be possible to give each cell a 1,2,3...N number or a (N,M) pair corresponding to the place of the grid cell in a study? 

That's  question to @humerh because ihs is something that has to be sorted out at server-side. Not sure if the added value (?) pays of the effort.

**Comment by DenoBeno** [comment]
Ah, I thought it's the same table used everywhere. If it's not reusable then yes, making all of them configurable is probably overkill.

In any case, I'm still not convinced that showing all data for all cells really helps the users. Min/max/average in the study area might be all they need. Download of complete data set is good though.

Considering the request for numbering the cells, this might make sense if these numbers are somehow also made visible in the map. Otherwise not.

**Comment by p-a-s-c-a-l** [comment]
Making tables configurable is not going to be supported, calculating Min/max/average is another issue.
