### ISSUE TITLE
Include information on Event Group/Type in RA/IA Table

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/table-components#8]
In the RA/IA Table, information on the selected HW Scenario Name ("Event Group" or "Event Type") is missing:

![grafik](https://user-images.githubusercontent.com/1788226/53577590-37cef300-3b76-11e9-9500-00b4a23c4084.png)

In particular, the name of the HW Scenario / Event is missing (low, medium, high, very high). See also the table below that defines 3 of the currently 4 event groups:

![grafik](https://user-images.githubusercontent.com/1788226/53577802-9d22e400-3b76-11e9-921b-b24086655c35.png)

@therter So maybe you can follow a similar approach as for the HC Table. 

However, in the JSON obtained from EMIKAT REST API this information on the HW Event name as well as RCP and time period is not available: @bernhardsk @humerh 

```json
{
  "name": "TAB Impact Results for Impact Assessment Drupal Table",
  "description": null,
  "columnnames": [
    "HAZARD_EVENT_ID",
    "HAZEVENT_NAME",
    "IMPACTCASE_ID",
    "EARTYPE_ID",
    "NAME",
    "QUANTITYUNIT",
    "VULNERABILITYCLASS_ID",
    "VULCLASS_NAME",
    "EXPOSEDQUANTITY",
    "DAMAGELEVEL1QUANTITY",
    "DAMAGELEVEL2QUANTITY",
    "DAMAGELEVEL3QUANTITY",
    "DAMAGELEVEL4QUANTITY",
    "DAMAGELEVEL5QUANTITY",
    "SZM_SZENARIO_REF"
  ],
  "rows": [
    {
      "rownum": 0,
      "values": [
        3,
        "Heat wave 32°, 6 days",
        1,
        1,
        "people",
        "number of people",
        26,
        "Age 15-65",
        337355.6662325851,
        236277.49887164417,
        87214.87361277906,
        12877.203135764006,
        950.6682674434248,
        35.75970062065402,
        2846
      ]
    },
```

IMHO it would make sense to introduce a Event Category (low, medum, ...), so that I could use that that as aggregation criteria for Scenario Analysis (see https://github.com/clarity-h2020/scenario-analysis/issues/9).

**Comment by p-a-s-c-a-l** [comment]
@therter BTW, why are there 5 damage classes in the JSON, 4 in the table and 6 defined:

![grafik](https://user-images.githubusercontent.com/1788226/53580111-33590900-3b7b-11e9-9a01-95ec5a5aff38.png)

**Comment by p-a-s-c-a-l** [comment]
@bernhardsk @humerh "**Age Group > 65**" is missing

**Comment by p-a-s-c-a-l** [comment]
@luis-meteogrid @bernhardsk @humerh @therter Can you please explain the relation of the values shown in the RA/IA Table (obtained from EMIKAT REST API) to the [HV-LE HW Data available on CLARITY Meteoroid Server](https://clarity.meteogrid.com/geoserver/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage?0) and to @RobAndGo 's Event Selection Table?

IMHO There are Layers for 4 **historical**  HW Events (why 4 and not 3?) on METEOGRID Server. In your table, there are 12 Events. Why?

**Comment by p-a-s-c-a-l** [comment]
@therter Status?

**Comment by therter** [comment]
The hazard can be selected to make the table clearer, but the event (frequent, occasional, rare) is still missing

**Comment by p-a-s-c-a-l** [comment]
Invalid for obvious reasons
